name: myproject
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - alphashape==1.3.1
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cascadio==0.0.16
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - click-log==0.4.0
      - colorama==0.4.6
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - exceptiongroup==2.2.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - flask==3.1.1
      - fonttools==4.59.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==9.4.0
      - ipython_pygments_lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - narwhals==2.1.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.2
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.3.0
      - prompt-toolkit==3.0.51
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyntcloud==0.3.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.4
      - retrying==1.4.2
      - rpds-py==0.27.0
      - rtree==1.4.0
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - setuptools==80.9.0
      - shapely==2.1.1
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - traitlets==5.14.3
      - trimesh==4.7.3
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - zipp==3.23.0
